version: "3.9"
services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    volumes:
      - ./datadog.yaml:/etc/datadog-agent/datadog.yaml
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /proc/:/host/proc/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ../.env
    networks:
      - default
  client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OTLP_GRPC_ADDR=datadog-agent:30080
    restart: always
    networks:
      - default
