version: "3.9"
services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    environment:
      DD_APM_ENABLED: true
      DD_APM_NON_LOCAL_TRAFFIC: true
      DD_LOGS_ENABLED: true
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: true
    volumes:
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /proc/:/host/proc/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ../.env
    networks:
      - default
  span-generator:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DD_AGENT_HOST: datadog-agent
      DD_TRACE_AGENT_PORT: 8126
      DD_ENV: docker-desktop
      DD_SERVICE: span-generator
    networks:
      - default
