name: Create and publish a Docker image

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_DOGSTATSD_CLIENT: ${{ github.repository }}-dogstatsd-client

jobs:
  build-and-push-dogstatsd-client-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_DOGSTATSD_CLIENT }}
      - name: Build and push gateway Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dogstatsd_client/Dockerfile
          push: true
          tags: ${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
